### ISSUE TITLE
接口被重定向了

### ISSUE THREAD

**Issue by White-S** [wudi1940/jd-seckill#1]
https://item-soa.jd.com/getwarebusiness?skuId='xxxx' 这个接口被重定向了

**Comment by wudi1940** [comment]
我测试了一下，好像没有问题，至少有的商品是没有问题的；确认下pid是否正确，给出更多的错误信息，可能部分产品jd优化反爬也有可能

**Comment by White-S** [comment]
pid没有问题，重复请求之后这个接口全被302了，其他电脑可以。

**Comment by White-S** [comment]
> 
> 
> 我测试了一下，好像没有问题，至少有的商品是没有问题的；确认下pid是否正确，给出更多的错误信息，可能部分产品jd优化反爬也有可能

调用这个接口全部302了，pid没有问题，一开始使用是没问题的，换个电脑能访问
